// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:017f121fceac1a24942d8fe2d16c99a1c7db72df194eb60e0a5f5c8acfe25846",
    "semanticFingerprint": "typebox-value-hash-v1:eabcceadb92f3a97",
    "defaultSettings": {
        "urlColor": "#87d7ff"
    }
} as const;

export default artifact;
