// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:becd796fbe542add8b4fe0622ab1c9535352eae581b8b1f0f5c20d800c7f18bc",
    "semanticFingerprint": "typebox-value-hash-v1:19c4d12b06845b62",
    "defaultSettings": {
        "mentions": []
    },
    "exampleSettings": {
        "mentions": [
            {
                "id": "environments",
                "trigger": "%",
                "completionSuffix": " ",
                "source": {
                    "type": "static",
                    "items": [
                        {
                            "name": "staging",
                            "description": "Staging environment"
                        },
                        {
                            "name": "production",
                            "description": "Production environment"
                        }
                    ]
                },
                "initialSuggestions": {
                    "strategy": "frecency",
                    "pinned": []
                }
            },
            {
                "id": "tickets",
                "trigger": "ticket:",
                "completionSuffix": " ",
                "source": {
                    "type": "command",
                    "mode": "array",
                    "command": "list-my-tickets",
                    "args": [
                        "--json"
                    ],
                    "cache": true,
                    "refreshOnStartup": true,
                    "cacheTtlMs": 300000
                },
                "initialSuggestions": {
                    "strategy": "frecency",
                    "pinned": []
                }
            }
        ]
    }
} as const;

export default artifact;
