// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:a9f8de1ecd8afec0554ba616ce75f9d331229cf4b0b99f74fa9f31c1b0f3b1f0",
    "semanticFingerprint": "typebox-value-hash-v1:0faf371b4e467377",
    "defaultSettings": {
        "cycleThinkingBackwardKey": null
    }
} as const;

export default artifact;
